sonar.organization=${SONAR_ORGANIZATION}
sonar.projectKey=${SONAR_PROJECT_KEY}
sonar.sources=src
sonar.tests=src,e2e
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/test/**,**/*.test.ts,**/*.test.tsx
